### ISSUE TITLE
1.20 version incompatibility / mislabel

### ISSUE THREAD

**Issue by magicfairybutterfly** [JustinTimeCuber/translucent-glass#1]
the error received :

> Mod 'Labelling Containers' (labellingcontainers) 1.2.1 requires any version between 1.20.1 (inclusive) and 1.21-(exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.20!

ran minecraft with only fabric api and the mod and still got this error, so i wont be including a mod list.

**Comment by JustinTimeCuber** [comment]
That is a different mod not made by me. Not sure how you ended up on this repo, but [this](https://github.com/Infinituum17/LabellingContainers) is the repo you are looking for.

Also, from a cursory glance, this doesn't even look like an issue as 1.2.1 is marked on their modrinth page as supporting only 1.20.1.

**Comment by magicfairybutterfly** [comment]
no idea how i ended up here either. sorry about that

>

**Comment by magicfairybutterfly** [comment]
> That is a different mod not made by me. Not sure how you ended up on this repo, but [this](https://github.com/Infinituum17/LabellingContainers) is the repo you are looking for.
> 
> Also, from a cursory glance, this doesn't even look like an issue as 1.2.1 is marked on their modrinth page as supporting only 1.20.1.

oh i just realized i wrote down the wrong incompatibility instead of translucent glass. its been a long day, but yes your mod was the one that was incompatible.

**Comment by JustinTimeCuber** [comment]
I can confirm that the mod is not working with 1.20, so you're right. Should be fixed now, although I wouldn't really recommend using 1.20 because 1.20.1 fixed some crashes and almost all mods are compatible anyway.
