### ISSUE TITLE
[Suggestions] Mo Glass textures

### ISSUE THREAD

**Issue by jaimee-88** [JustinTimeCuber/translucent-glass#5]
![image](https://github.com/user-attachments/assets/5135ed02-fdd8-4d33-832f-be9c90dffcf0)
I really love the textures of glass blocks in this mod, making it work with Mo Glass stairs and slabs would be cool

**Comment by JustinTimeCuber** [comment]
I submitted a patch to make this work on their end, if it's accepted I'll put out a new release with textures to make it fully compatible

**Comment by JustinTimeCuber** [comment]
Translucent Glass v0.2.0 will be compatible with Mo Glass v1.10
