### ISSUE TITLE
Invisible Weather

### ISSUE THREAD

**Issue by Terraphice** [JustinTimeCuber/translucent-glass#7]
When looking through glass, weather effects (rain) don't appear. Feels a bit silly to come inside while it's raining heavily, only for it to look clear as day out of the window.

**Comment by JustinTimeCuber** [comment]
This mod makes the game treat regular glass the same as stained glass and other translucent blocks. Using Fabulous graphics should fix your issue.

**Comment by Terraphice** [comment]
Ah, that makes sense then. Unfortunately that doesn’t fix my issue, but it appears that’s just something wrong with Sodium’s rendering that is inconsistently fixed across different versions. Thanks for letting me know.
